version: '3.7'

services:
  database:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - database-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: husion_labeling
      POSTGRES_USER: user
    ports:
      - 5432:5432

  web:
    build:
      context: ./
    ports:
      - 8000:8000
volumes:
  database-storage: